server:
  port: 8080
spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/authdb
    username: root
    password:
  security:
    bcrypt:
      strength: 12
jwt:
  secret: mySecretKey1234567890abcdef1234567890abcdef
  expiration: 86400000 # 1 día en milisegundos